IMAGE_SIZE: 64
SEQUENCE_LENGTH: 20
MAX_WORKERS: 2
SEED: 42
BATCH_SIZE: 32
EPOCHS: 1
LEARNING_RATE: 0.001
TRAINING_RATIO: 0.8
TESTING_RATIO: 0.2
EARLY_STOPPING_PATIENCE: 3

# augmentation
ROTATE_FACTORS: [30,-30,20,-20,10,-10]
SCALE_FACTORS: [1.1,1.2,1.3,0.9,0.8,0.7]
FLIP_FACTOR: true

SHUFFLE_BUFFER_SIZE: 1000
CHANNELS: 1
VERBOSE: true

NUM_CLASSES: 24
SAVE_PLOTS: true
