image_extraction:
  source_dir: dataset/VA-dataset
  destination_dir: dataset/imageDataset
  image_format: jpg

splitting_dataset:
  source_dir: dataset/imageDataset
  destination_dir: dataset/splitDataset
  split_dir_dict_path: dataset/splitDataset/split_dir_dict.npy

data_augmentation:
  source_dir: dataset/splitDataset
  destination_dir: dataset/augmentedDataset

load_dataset:
  source_dir: dataset/augmentedDataset

prepare_callbacks:
  best_checkpoint_path: dataset/results/model_checkpoint/model_best/best_model.keras
  checkpoint_path: dataset/results/model_checkpoint/models
  history_path: dataset/results/model_checkpoint/history.txt

base_model:
  base_model_path: dataset/model/base_model.keras
  model_architecture_plot_path: dataset/results/base_model_architecture.png

training:
  base_model_path: dataset/model/base_model.keras
  history_path: dataset/results/model_checkpoint/history.txt
  checkpoint_path: dataset/results/model_checkpoint/models
  loss_curve_path: dataset/results/loss_curve.png
  accuracy_curve_path: dataset/results/accuracy_curve.png

evaluation:
  best_model_path: dataset/results/model_checkpoint/model_best/best_model.keras
  confusion_matrix_path: dataset/results/confusion_matrix.png
  classification_report_path: dataset/results/classification_report.txt